### PR TITLE
Add path object

### PR DESCRIPTION
**Pull request by KutsenkoA**
Add require('path') to avoid ReferenceError: path is not defined in line 34-35

### CODE REVIEW

**Comment by sindresorhus** [comment]
// @jansensan

**Comment by jansensan** [comment]
Oh, sorry for that inconvenience. Thanks for fixing that.

**Comment by cookch10** [comment]
Experiencing this `ReferenceError: path is not defined` error.  Is there a plan for releasing this fix in the near future?

**Comment by cookch10** [comment]
Fixed for me in latest release, `1.5.1`.  Thank you!

**Pull request merged**
