### PR TITLE
bump jscs dep

### LINKED ISSUE #86: Update jscs lib
Hi all,
just curious about supporting of [new JSCS version](http://jscs.info/changelog.html#version-1-13-1) which supports more new ES2015/ES6 features, like [destructuring](https://hacks.mozilla.org/2015/05/es6-in-depth-destructuring/).

For example,

````javascript
function someFn(a, b, {c = 1, d = 2} = {}) {
    // some code
}
````

Current version of JSCS (1.12) which gulp-jscs depends on, throws a ParseError because Esprima parser doesn't support syntax like this.

Maybe there is some workaround on this?

Thanks so much

### PR DESCRIPTION
**Pull request by Neurostep**
It fixes #86

### CODE REVIEW

**Comment by Slayer95** [comment]
http://semver.org/

**Comment by Neurostep** [comment]
@Slayer95 Do you mean that I should bump gulp-jscs minor version as well (1.6.0 -> 1.7.0)? Well, I guess it should be done by maintainer. Anyway, I can do it if I understand you correctly.

**Comment by Slayer95** [comment]
No.

`"^1.12.0"`` already covers the latest version. You just need to run ``npm update.``

**Comment by Neurostep** [comment]
Yeah, my bad, event `1.13.1` doesn't support new major esprima version (which fixes destructuring issue described in #87). I should first address it to [JSCS repo](https://github.com/jscs-dev/node-jscs)

@Slayer95 Thanks for your participating

**Comment by sindresorhus** [comment]
https://nodesource.com/blog/semver-tilde-and-caret

**Pull request closed without merging**
