### PR TITLE
Update to JSCS 3.0

### LINKED ISSUE #109: Update to JSCS 3.0
Hello,

Could you please update gulp-jscs to make it work with latest major version of JSCS, 3.0.3 ? Forcing the update did not work, as it seems that some code in the reporters must be changed.

Thanks

### PR DESCRIPTION
**Pull request by acburdine**
closes #109
- update jscs to 3.0
- fix reporter file name and test issue

### CODE REVIEW

**Comment by acburdine** [comment]
@sindresorhus any chance on getting this merged soon? I need this for several of my projects 😄

**Comment by sindresorhus** [comment]
@mikesherov Anything breaking changes in v3 that this plugin might be affected by?

**Comment by acburdine** [comment]
@sindresorhus I know there are some that would affect various projects _using_ gulp-jscs (a couple of rules were dropped and cause errors if they are included in the .jscsrc). However, I don't think any affect this plugin itself.

**Comment by acburdine** [comment]
FWIW, I tested this with several other of my projects and it worked fine

**Comment by sindresorhus** [comment]
Alright

**Pull request merged**
